name: CI workflow

# Trigger the workflow on push events to the main branch
# and pull requests targeting the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define a lightweight Python environment using a Docker container
    container:
      image: python:3.9-slim

    # Steps to execute within the job
    steps:
      # Checkout the repository content
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the codebase using flake8
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
          
      # Run unit tests using nose
      - name: Run unit tests with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
